import React from 'react'

export const Experience = () => {
  return (
    <div id="main">

							<section className="post">
								<header className="major">
									<h1>Experience</h1>
								</header>
								<ul >
									<li style={{listStyleType:"none"}}><b> 2017 - Eltel Networks Energetyka S.A. Olsztyn R&D technician</b>
										<p>Two-month internship during which I researched CYMCAP application and written brief tutorial for other sta members. Wrote the software for calculating EM fields, Inducing voltages etc.. Studied thermal phenomena of underground cables in surrounding of different type of soil layers.</p></li>
										
									<li style={{listStyleType:"none"}}><b> 2018-2019 - Eltel Networks Energetyka S.A. Olsztyn R&D engineer</b>
									<p>
										One year of full-time job during which I improved all software and tutorials written before and create new ones. I also modeled cables and prepared simulations of actual branch projects using CYMCAP, teach other sta members CYMCAP and learned others CYME software. I wrote technical specification of ordered equipment and create documentation of projects and used my created software in solving actual branch projects.
									</p>
								</li>
								</ul>

								<header className="major">
									<h1>Education</h1>
								</header>
								<ul >
									<li style={{listStyleType:"none"}}><b> 2014-2018 B.Sc. Majoring in Technical Physics Gdansk University of Technology</b>
										<p> <b>Graduate Thesis: Calculations of magnetic field intensity generated by arbitrary systems of underground cables and overhead lines</b></p></li>
										
								</ul>

								
							</section>

					</div>
  )
}